apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jaeger
  namespace: seldon
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: simplest-query
              servicePort: 16686