apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraudtfflow
  labels:
    app: fraudtfflow
spec:
  replicas: 20
  selector:
    matchLabels:
      app: fraudtfflow
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fraudtfflow
    spec:
      containers:
        - name: serving
          image: tensorflow/serving:1.14.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8500
              name: grpc
              protocol: TCP
            - containerPort: 8501
              name: http
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 1
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            tcpSocket:
              port: htttp
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 1Gi
          env:
            - name: "AWS_REGION"
              value: "eu-west-1"
            - name: "S3_REGION"
              value: "eu-west-1"
            - name: "S3_ENDPOINT"
              value: "s3.eu-west-1.amazonaws.com"
            - name: "S3_USE_HTTPS"
              value: "1"
            - name: "S3_VERIFY_SSL"
              value: "1"
            - name: "AWS_ACCESS_KEY_ID"
              valueFrom: { secretKeyRef: { name: "s3-credentials", key: "accessKey" } }
            - name: "AWS_SECRET_ACCESS_KEY"
              valueFrom: { secretKeyRef: { name: "s3-credentials", key: "secretKey" } }
            - name: "MODEL_BASE_PATH"
              value: "s3://fdp-killrweather-data/kubeflow/fraud_detection/model"
            - name: "MODEL_NAME"
              value: "fraud"
      volumes:
        - name: secret-volume
          secret:
            secretName: s3-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: fraudtfflow
spec:
  selector:
    app: fraudtfflow
  ports:
    - name: grpc
      protocol: TCP
      port: 8500
      targetPort: 8500
    - name: http
      protocol: TCP
      port: 8501
      targetPort: 8501
